version: "3.8"

services:
  app:
    build: .
    container_name: rag_app
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./chroma_db:/app/chroma_db 
      - .:/app  
    command: ["python", "main.py"]
    restart: unless-stopped

